### ISSUE TITLE
macOS home directory not being expanded

### ISSUE THREAD

**Issue by powerllama** [vinavfx/nuke_util#1]
Hello friend. Was running into an issue with your comfyUI plugin for Nuke, and I tracked it down to the `nuke_util.py` file. You have a check for Linux and Windows, but not one for macOS aka `Darwin`. So on macOS it skips the initial test and goes straight to the windows test where it starts escaping backslashes and stuff.

I've made the change in my local copy and this works but I'm not sure how to do all the fun OSS stuff like opening a pull request.

On line 12 of `nuke_util.py` you can change 

```
if platform.system() == 'Linux':
```

to

```
if platform.system() == 'Linux' or platform.system() == 'Darwin':
```

And all should be good with macOS.

Edit two: i figured out how to make a pull request

**Comment by vinavfx** [comment]
71c49c7
